
import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    sku: 'FISH-NEON-XL',
    name: 'Neon Tetra (XL)',
    category: 'Fish',
    price: 40,
    weight: 0.05,
    stock: 500,
    featured: true,
    description: 'Bright and energetic schooling fish perfect for any community tank.',
    image: 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    sku: 'FISH-GUPPY-ASM',
    name: 'Guppy (Assorted Colors)',
    category: 'Fish',
    price: 25,
    weight: 0.03,
    stock: 300,
    featured: true,
    description: 'Beautiful assorted guppies that add a splash of color to your aquarium.',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    sku: 'FISH-BETTA-M',
    name: 'Betta Splendens (Male)',
    category: 'Fish',
    price: 120,
    weight: 0.08,
    stock: 150,
    featured: false,
    description: 'Majestic male Bettas with flowing fins and vibrant personalities.',
    image: 'https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    sku: 'FISH-DISC-BLU',
    name: 'Discus Fish (Blue Diamond)',
    category: 'Fish',
    price: 1200,
    weight: 0.2,
    stock: 50,
    featured: true,
    description: 'The king of the aquarium. Stunning blue diamond discus for high-end setups.',
    image: 'https://images.unsplash.com/photo-1571752726703-5e7d1f6a986d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '5',
    sku: 'SUB-ADA-9L',
    name: 'ADA Amazonia Ver. 2 (9L)',
    category: 'Substrates',
    price: 3800,
    weight: 9,
    stock: 12,
    featured: false,
    description: 'Premium soil for aquascaping, providing essential nutrients for plants.',
    image: 'https://images.unsplash.com/photo-1516553174826-d05833723cd4?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '6',
    sku: 'SUB-FLR-BLK',
    name: 'Seachem Flourite Black Sand (7kg)',
    category: 'Substrates',
    price: 2200,
    weight: 7,
    stock: 20,
    featured: false,
    description: 'Specially fracted stable porous clay gravel for the natural planted aquarium.',
    image: 'https://images.unsplash.com/photo-1620230613271-e94098939a38?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '7',
    sku: 'PLNT-ANUB-PET',
    name: 'Anubias Nana Petite',
    category: 'Plants',
    price: 350,
    weight: 0.1,
    stock: 25,
    featured: true,
    description: 'Hardy, slow-growing plant that thrives in almost any conditions.',
    image: 'https://images.unsplash.com/photo-1509100194014-d49809396daa?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '8',
    sku: 'PLNT-JAVA-MOS',
    name: 'Java Moss Mat',
    category: 'Plants',
    price: 200,
    weight: 0.05,
    stock: 40,
    featured: false,
    description: 'Versatile moss that attaches to rocks and wood, creating a natural look.',
    image: 'https://images.unsplash.com/photo-1444491741275-3747c53c99b4?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '9',
    sku: 'FLTR-EHM-2217',
    name: 'Eheim 2217 Classic Filter',
    category: 'Filters',
    price: 14500,
    weight: 6,
    stock: 5,
    featured: false,
    description: 'Reliable canister filter for crystal clear water and biological balance.',
    image: 'https://images.unsplash.com/photo-1520107449437-6a4a42ddabb7?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '10',
    sku: 'FLTR-FLV-FX6',
    name: 'Fluval FX6 Canister Filter',
    category: 'Filters',
    price: 28000,
    weight: 8,
    stock: 3,
    featured: true,
    description: 'Heavy-duty filtration for large aquariums up to 400 gallons.',
    image: 'https://images.unsplash.com/photo-1534123235357-19fd75535805?auto=format&fit=crop&q=80&w=800',
  }
];
